export const ADD_PRODUCT_TO_CART = 'ADD_TO_CART';
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS';

export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';

export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const SET_CART_LOADING = 'SET_CART_LOADING';

export const CLEAR_CART = 'CLEAR_CART';

export const LOAD_CART_DATA = 'LOAD_CART_DATA';
