export const GET_INITIAL_PRODUCTS = 'GET_INITIAL_PRODUCTS';

export const SET_PC_BUILDER_LOADING = 'SET_PC_BUILDER_LOADING';

export const ADD_SELECTED_PRODUCT = 'ADD_SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
