export const GET_INITIAL_PRODUCTS = 'GET_INITIAL_PRODUCTS';

export const CLEAR_PC_BUILDER_PRODUCTS = 'CLEAR_PC_BUILDER_PRODUCTS';

export const SET_PC_BUILDER_LOADING = 'SET_PC_BUILDER_LOADING';

export const GET_SUGGESTED_MOTHERBOARD = 'GET_SUGGESTED_MOTHERBOARD';
export const GET_SUGGESTED_COOLER = 'GET_SUGGESTED_COOLER';
export const GET_SUGGESTED_MEMORY = 'GET_SUGGESTED_MEMORY';

export const ADD_SELECTED_PRODUCT = 'ADD_SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
